GET http://127.0.0.1:8000/auth/users/me HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYxMzYwOTA3LCJpYXQiOjE3NjEzNTczMDcsImp0aSI6IjU3NmZiOTcyOGQyYTQ0ZGVhNTdjZDY4YTE1YzhiMjhlIiwidXNlcl9pZCI6IjEifQ.7SxgG2N2Lk5pmBJ8YifhxlFbPaFTfVmzdwLds-70WEw

###
POST http://127.0.0.1:8000/auth/jwt/verify HTTP/1.1
Content-Type: application/json

{
    "token": "sdfsdfsdfs"
}

###
POST http://127.0.0.1:8000/auth/jwt/create/ HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "password"
}
